version: '3'
services: 
    postgres:
        image: 'postgres:latest'
        restart: always
        environment: 
          - POSTGRES_PASSWORD 
          - POSTGRES_PORT
        ports:
          - '4000:5432'
        volumes:
          - /home/tkuczak/index-performance:/home/postgres
